### ISSUE TITLE
docs are wrong: double wrapping main() throws error

### ISSUE THREAD

**Issue by troygoode** [blx/jqllib-fetch#1]
In the README.md you call jqlFetch like so:

```javascript
fetch(`function main() { return Events(...)... }`)
```

This won't work because in your source you're redefining the value passed in as:

```javascript
jql = `function main() { ${jql} }`
```

This causes your `main` function to be wrapped by another `main` function, which MixPanel will not support. My suggestion is to remove the "magic" autowrap, but you could also just update the docs.

**Comment by blx** [comment]
Hi! You're completely right. I thought I'd fixed that.

I like the magic wrapping, because it makes the JQL strings easier to compose outside of jqllib-fetch, but have added a guard to ensure your JQL is not already wrapped in main().

Thanks!
